web_app/auth.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from .models import Users, db

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template("login.html")

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = bool(request.form.get('remember'))

    user : Users = Users.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        return jsonify({"success": False, "message": f"Erreur : {"incorect password" if user else "mail inconnue"}"})

    login_user(user, remember=remember, force=True)
    return redirect(url_for('views.index'))

@auth.route('/signup')
def signup():
    return render_template('signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    if user := Users.query.filter_by(email=email).first():
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    new_user = Users(email=email, name=name, password=generate_password_hash(password))
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index'))

web_app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
      {% block title %}{% endblock title %}
    </title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

    {% block head %}{% endblock head %}
  </head>
  <body>
    <nav>
      <button id="narrow-menu-button">
        &equiv;
      </button>

      <ul>
        <li><a href="/">Accueil</a></li>
        <li><a href="/herd">Troupeau</a></li>
        <li><a href="/reproduction">Reproduction</a></li>
        <li><a href="/medicine_cabinet">Pharmacie</a></li>
        <li><a href="/settings">Paramètres</a></li>
        <li>
          <a href="/logout">
            <img src="{{ url_for('static', filename='img/logout.svg') }}" alt="Logout icon">
          </a>
        </li>
      </ul>
    </nav>

    <main>
      {% block content %}
      {% endblock content %}
    </main>

    <script>
      const menuButton = document.querySelector("button#narrow-menu-button");
      const menu = document.querySelector("nav ul");

      menuButton.addEventListener("click", () => {
        if (menu.style.height == "50vh") {
          menu.style.height = "0";
        } else {
          menu.style.height = "50vh";
        }
      });

      const collapsibles = document.querySelectorAll("section.collapsible");

      collapsibles.forEach((collapsible) => {
        const collapsibleTitle = collapsible.children[0];

        collapsibleTitle.addEventListener("click", () => {
          if (collapsible.getAttribute("aria-expanded") == "false") {
            collapsible.setAttribute("aria-expanded", "true");
          } else {
            collapsible.setAttribute("aria-expanded", "false");
          }
        });
      });
    </script>

    {% block js %}
    {% endblock js %}
  </body>
</html>

web_app/templates/cow.html
{% extends 'base.html' %}

{% block title %}Cow {{ cow.cow_id }} | BioFarm Monitor{% endblock title %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/cow.css') }}">
{% endblock head %}

{% block content %}
  <h1>Vache numéro {{ cow.cow_id }} </h1>

  <section>
    <ul>
      <li>Date de naissance: {{ date_to_str(cow.born_date) }}</li>
    </ul>

    <div id="action-buttons-wrapper">
      <button id="change-button">Modifier</button>
      <button id="delete-button">Supprimer</button>
    </div>
  </section>

  <section class="collapsible" aria-expanded="false">
    <h2>&nbsp;Historique de reproduction</h2>

    <div class="collapsible-content">
      <span>Aucun élément</span>
    </div>
  </section>

  <section class="collapsible" aria-expanded="false">
    <h2>&nbsp;Historique médical</h2>

    <div class="collapsible-content">
      <span>Aucun élément</span>
    </div>
  </section>
{% endblock %}

web_app/templates/herd.html
{% extends 'base.html' %}

{% block title %}Troupeau | BioFarm Monitor{% endblock title %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/herd.css') }}">
{% endblock head %}

{% block content %}
  <h1>Gestion du troupeau</h1>

  <section>
    <h2>Liste des vaches</h2>

    <div id="id-filter-box">
      <input type="text" placeholder="Filtrer par identifiant">
    </div>

    <table cellspacing="0">
      <thead>
        <tr>
          <th>Identifiant</th>
          <th>Date de naissance</th>
          <th>
            <button id="add-cow-button">+</button>
          </th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </section>

  <div id="overlay"></div>

  <div class="popup">
    <div class="popup-header">
      <h3>Acquisition d'une vache</h3>
      <button>&times;</button>
    </div>

    <p>ATTENTION&nbsp;: ce fromulaire sert à enregistrer une acquisition et non
      une naissance.</p>

    <form action="{{ url_for('herd.acquire') }}" method="POST">
      <label for="id">Numéro de la vache&nbsp;:</label>
      <input name="id" type="number" required>

      <label for="birth_date">Date de naissance&nbsp;:</label>
      <input name="birth_date" type="date" required>

      <button type="submit">Ajouter</button>
    </form>
  </div>

  <template id="herd-table-template">
    <tr>
      <td><a>Cow ID</a></td>
      <td>Date de naissance</td>
      <td></td>
    </tr>
  </template>
{% endblock content %}

{% block js %}
  <script src="{{ url_for('static', filename='js/herd.js') }}"></script>
{% endblock js %}

web_app/templates/index.html
{% extends 'base.html' %}

{% block title %}Accueil | BioFarm Monitor{% endblock title %}

{% block content %}
  <h1>Accueil</h1>

  <section>
    <h2>Événements à venir</h2>

    <h3>Préparations de vêlage</h3>

    <span>Aucun événement planifié</span>

    <h3>Tarissements</h3>

    <span>Aucun événement planifié</span>

    <h3>Vêlages</h3>

    <span>Aucun événement à venir</span>
  </section>
{% endblock %}

web_app/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
  </head>
  <body>
    <form action="{{ url_for('auth.login_post') }}" method="POST">
      <h1>Bienvenue sur BioFarm-Monitor</h1>

      <div id="error-div">
        <span>test</span>
      </div>

      <input type="email" id="email" name="email" placeholder="E-mail" autocomplete="off">
      <input type="password" id="password" name="password" placeholder="Mot de passe">

      <button type="submit">Entrer</button>
    </form>

    <script src="{{ url_for('static', filename='js/login.js') }}"></script>
  </body>
</html>

web_app/templates/medicine-cabinet.html
{% extends 'base.html' %}

{% block title %}Pharmacie | BioFarm Monitor{% endblock title %}

web_app/templates/reproduction.html
{% extends 'base.html' %}

{% block title %}Reproduction | BioFarm Monitor{% endblock title %}

web_app/templates/settings.html
{% extends 'base.html' %}

{% block title %}Troupeau | BioFarm Monitor{% endblock title %}